# Generated by Django 3.2.9 on 2021-11-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_mografia_monografia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monografia',
            name='Auto',
        ),
        migrations.AddField(
            model_name='monografia',
            name='Area',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='monografia',
            name='Autor',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='monografia',
            name='Banca',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='monografia',
            name='Curso',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='monografia',
            name='Data',
            field=models.DateField(default=True),
        ),
        migrations.AddField(
            model_name='monografia',
            name='Formato',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='monografia',
            name='Numero_de_Paginas',
            field=models.CharField(default=' ', max_length=3),
        ),
        migrations.AddField(
            model_name='monografia',
            name='Universidade',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='monografia',
            name='Url',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='Orientador',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='Titulo',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
