# Generated by Django 3.2.9 on 2021-11-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211114_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monografia',
            name='Data',
            field=models.CharField(max_length=10),
        ),
    ]
