# Generated by Django 3.2.9 on 2021-11-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211114_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monografia',
            name='Data',
            field=models.CharField(max_length=300),
        ),
    ]
