# Generated by Django 3.2.9 on 2021-11-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_monografia_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monografia',
            name='Data',
            field=models.CharField(max_length=10),
        ),
    ]
