# Generated by Django 3.2.9 on 2021-11-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_monografia_data'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='monografia',
            table='repositoriodemonografias',
        ),
    ]
