# Generated by Django 3.2.9 on 2021-12-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_monografia_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monografia',
            name='Data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='Formato',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='Numero_de_Paginas',
            field=models.IntegerField(),
        ),
    ]
