# Generated by Django 3.2.9 on 2021-11-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_monografia_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monografia',
            name='Data',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='Numero_de_Paginas',
            field=models.IntegerField(max_length=4),
        ),
    ]
