# Generated by Django 3.2.9 on 2021-12-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20211207_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monografia',
            name='Formato',
            field=models.CharField(choices=[('P', 'P'), ('W', 'W'), ('Z', 'Z')], max_length=100),
        ),
    ]
